---
engines:
  eslint:
    enabled: true
    exclude_paths:
      - "src/http/ui/dist/**"
      - "src/http/ui/node_modules/**"
    base_sub_dir: "src/http/ui"
  typescript:
    enabled: true
    base_sub_dir: "src/http/ui"
